import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import Header from "./components/header";
import Footer from "./components/footer";
import Whatsapp from "./components/whatsapp-button";
import ProductsPage from "./components/discounted_product";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <link rel="stylesheet" href="./assets/css/vendor/bootstrap.min.css" />
      {/* Font Awesome CSS */}
      <link rel="stylesheet" href="./assets/css/vendor/font.awesome.min.css" />
      {/* Linear Icons CSS */}
      <link rel="stylesheet" href="./assets/css/vendor/linearicons.min.css" />
      {/* Swiper CSS */}
      <link
        rel="stylesheet"
        href="./assets/css/plugins/swiper-bundle.min.css"
      />
      {/* Animation CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/animate.min.css" />
      {/* Jquery ui CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/jquery-ui.min.css" />
      {/* Nice Select CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/nice-select.min.css" />
      {/* Magnific Popup */}
      <link rel="stylesheet" href="./assets/css/plugins/magnific-popup.css" />
      {/* Main Style CSS */}
      <link rel="stylesheet" href="./assets/css/style.css" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Whatsapp />
        <Header /> {/* Add the Header component here */}
        {children}
        <Footer />


      </body>
    </html>
  );
}
