import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <meta charSet="utf-8" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <title>Han Çiçekçilik-Ana Sayfa</title>
      <meta name="robots" content="noindex, follow" />
      <meta name="description" content="" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      {/* Favicon */}

      {/* CSS
    ============================================ */}
      {/* Bootstrap CSS */}
      <link rel="stylesheet" href="./assets/css/vendor/bootstrap.min.css" />
      {/* Font Awesome CSS */}
      <link rel="stylesheet" href="./assets/css/vendor/font.awesome.min.css" />
      {/* Linear Icons CSS */}
      <link rel="stylesheet" href="./assets/css/vendor/linearicons.min.css" />
      {/* Swiper CSS */}
      <link
        rel="stylesheet"
        href="./assets/css/plugins/swiper-bundle.min.css"
      />
      {/* Animation CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/animate.min.css" />
      {/* Jquery ui CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/jquery-ui.min.css" />
      {/* Nice Select CSS */}
      <link rel="stylesheet" href="./assets/css/plugins/nice-select.min.css" />
      {/* Magnific Popup */}
      <link rel="stylesheet" href="./assets/css/plugins/magnific-popup.css" />
      {/* Main Style CSS */}
      <link rel="stylesheet" href="./assets/css/style.css" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >{/* Add the Header component here */}
        {children}
      </body>
    </html>
  );
}

