import Sidebar from "./companents/sidebar/sidebar";
import Footer from "./companents/footer/footer";

export const metadata = {
  title: "Han Çiçek Admin paneli",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        {children}
        <Footer />
      
      </body>
    </html>
  );
}
